### ISSUE TITLE
Multiple slices result in an error

### ISSUE THREAD

**Issue by jakirkham** [soft-matter/pims#262]
Seems one is unable to take multiple slices at once. See snippet below for details. Also the `conda` environment used to demonstrate this is included as well.

Code:

<details>

```python
>>> import pims
>>> print(pims.open("reg.tif")[0:1])
Sliced TiffStack_tifffile. Original repr:
    <Frames>
    Source: reg.tif
    Length: 150 frames
    Frame Shape: (110, 120)
    Pixel Datatype: H
>>> print(pims.open("reg.tif")[0:1, 0:110, 0:120])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda2/envs/pims/lib/python2.7/site-packages/slicerator.py", line 185, in __getitem__
    indices, new_length = key_to_indices(i, len(self))
  File "/opt/conda2/envs/pims/lib/python2.7/site-packages/slicerator.py", line 307, in key_to_indices
    raise IndexError("Keys out of range")
IndexError: Keys out of range
```

</details>
<br>

Environment:

<details>

```yaml
name: pims
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py27_0
- conda-forge::freetype=2.7=1
- conda-forge::jinja2=2.9.5=py27_0
- conda-forge::jpeg=9b=0
- conda-forge::libpng=1.6.28=0
- conda-forge::libtiff=4.0.6=7
- conda-forge::markupsafe=0.23=py27_1
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py27_blas_openblas_200
- conda-forge::olefile=0.44=py27_0
- conda-forge::openblas=0.2.19=2
- conda-forge::openssl=1.0.2k=0
- conda-forge::pillow=4.1.0=py27_0
- conda-forge::pims=0.3.3=py27_1
- conda-forge::pip=9.0.1=py27_0
- conda-forge::python=2.7.13=0
- conda-forge::readline=6.2=0
- conda-forge::scipy=0.19.0=np112py27_blas_openblas_200
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::slicerator=0.9.8=py27_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::tifffile=0.12.0=np112py27_0
- conda-forge::tk=8.5.19=1
- conda-forge::wheel=0.29.0=py27_0
- conda-forge::xz=5.2.2=0
- conda-forge::zlib=1.2.11=0
- libgfortran=3.0.0=1
prefix: /opt/conda2/envs/pims
```
</details>

**Comment by caspervdw** [comment]
Thanks for the report. 

PIMS wasn't built for slicing along lazy and greedy axes at the same time. I think that `dask` would be the best way to go to work with these cases.

With the current version of PIMS, you should use a pipeline function for lazy processing (e.g. cropping) of individual images.

```
    @pipeline
    def crop(image):
        return image[...]
    
    cropped = crop(reader[0:1])
```

**Comment by jakirkham** [comment]
Ok, cool. So basically I was doing something that is unsupported. Feel free to close.

> I think that `dask` would be the best way to go to work with these cases.

Interestingly I was trying to generalize slice handling to make it easier to ingest different data formats into Dask.

> With the current version of PIMS, you should use a pipeline function for lazy processing (e.g. cropping) of individual images.

Not sure if this would be the cleanest approach given what I was doing. However, would it recognize if the crop was a no-op?
