### ISSUE TITLE
Pickling issue with TIFF stack

### ISSUE THREAD

**Issue by jakirkham** [soft-matter/pims#265]
Running into an issue opening a TIFF file and pickling it. Code snippet and `conda` environment used to produce the issue provided below.

Example:

<details>

```python
>>> import pickle
>>> import pims
>>> f = pims.open("tiff_stack.tif")
>>> pickle.dumps(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 621, in _batch_appends
    save(x)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/copy_reg.py", line 74, in _reduce_ex
    getstate = self.__getstate__
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/site-packages/tifffile/tifffile.py", line 3460, in __getattr__
    return self[name]
KeyError: '__getstate__'
```

</details>

<br>
Environment:
<br>
<br>

<details>

```yaml
name: pimsenv
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py27_0
- conda-forge::freetype=2.7=1
- conda-forge::jinja2=2.9.5=py27_0
- conda-forge::jpeg=9b=0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::libpng=1.6.28=0
- conda-forge::libtiff=4.0.6=7
- conda-forge::markupsafe=0.23=py27_1
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py27_blas_openblas_200
- conda-forge::olefile=0.44=py27_0
- conda-forge::openblas=0.2.19=2
- conda-forge::openssl=1.0.2k=0
- conda-forge::pillow=4.1.0=py27_0
- conda-forge::pims=0.3.3=py27_1
- conda-forge::python=2.7.13=0
- conda-forge::readline=6.2=0
- conda-forge::scipy=0.19.0=np112py27_blas_openblas_200
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::slicerator=0.9.8=py27_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::tifffile=0.12.0=np112py27_0
- conda-forge::tk=8.5.19=1
- conda-forge::xz=5.2.2=0
- conda-forge::zlib=1.2.11=0
```

</details>

**Comment by caspervdw** [comment]
This seems to be a `tifffile` issue: have you tried pickling `f._tiff`? I think it does not work because this tifffile object is not picklable.

Pickling of file handles is, in the general case, not possible. We could attempt to solve this at `pims` by just presenting filename and all other args needed to construct the reader at a custom `__getstate__`, `__setstate__`. But that would only be worth something in combination with the datafile.

**Comment by jakirkham** [comment]
> This seems to be a tifffile issue: have you tried pickling f._tiff? I think it does not work because this tifffile object is not picklable.

Indeed that also fails.

<details>

```python
>>> pickle.dumps(f._tiff)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 621, in _batch_appends
    save(x)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/zopt/conda2/envs/pimsenv/lib/python2.7/copy_reg.py", line 77, in _reduce_ex
    raise TypeError("a class that defines __slots__ without "
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled
```

</details>

<br>

> Pickling of file handles is, in the general case, not possible. We could attempt to solve this at pims by just presenting filename and all other args needed to construct the reader at a custom `__getstate__`, `__setstate__`.

Could be interesting. So just reopen the file on unpickling?

> But that would only be worth something in combination with the datafile.

Meaning that the same file needs to be present on the system in the same place? Yes. I think this is unavoidable.
