### ISSUE TITLE
ImageSequence arguments error

### ISSUE THREAD

**Issue by ghattab** [soft-matter/pims#284]
Hi there, I have been coming across the following problem:

```
>>> import pims
>>> pims.__version__
u'0.4.1'

>>> pims.ImageSequence("*.tif")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pims/image_sequence.py", line 97, in __init__
    tmp = self.imread(self._filepaths[0], **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/pims/image_sequence.py", line 125, in imread
    return imread(filename, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2193, in imread
    return _imread(*args, **kwargs)
TypeError: imread() got an unexpected keyword argument 'plugin'
```

The current directory does indeed contain n TIF files.
I tried all the formats reported in the documentation [here](https://soft-matter.github.io/pims/v0.4/image_sequence.html) to no avail.
I appreciate any insight into this matter. Thx.

**Comment by ghattab** [comment]
Went through updating and removing packages one by one to see what's causing what.
The fix was to uninstall and re-install scikit-image to `'0.11dev'`
The imread() behavior is fixed and the image sequence loads properly:

```
>>> pims.ImageSequence("Case*tif")
<Frames>
Source: /Users/gh/Desktop/simulated-data/DS1/Case*tif
Length: 25 frames
Frame Shape: (1080, 1920, 3)
Pixel Datatype: uint8 
```
