### ISSUE TITLE
PyAv export is broken with PyAv 0.4

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/pims#302]
Test output:

```
ERROR: test_quality_h264 (pims.tests.test_display.TestExportPyAV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/soft-matter/pims/pims/tests/test_display.py", line 159, in test_quality_h264
    quality=0)
  File "/home/travis/build/soft-matter/pims/pims/display.py", line 160, in export_pyav
    packet = stream.encode()
  File "av/stream.pyx", line 128, in av.stream.Stream.encode
  File "av/codec/context.pyx", line 296, in av.codec.context.CodecContext.encode
  File "av/codec/context.pyx", line 209, in av.codec.context.CodecContext._send_frame_and_recv
  File "av/utils.pyx", line 105, in av.utils.err_check
av.AVError: [Errno 541478725] End of file
======================================================================
ERROR: test_quality_mpeg4 (pims.tests.test_display.TestExportPyAV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/soft-matter/pims/pims/tests/test_display.py", line 148, in test_quality_mpeg4
    quality=1)
  File "/home/travis/build/soft-matter/pims/pims/display.py", line 160, in export_pyav
    packet = stream.encode()
  File "av/stream.pyx", line 128, in av.stream.Stream.encode
  File "av/codec/context.pyx", line 296, in av.codec.context.CodecContext.encode
  File "av/codec/context.pyx", line 209, in av.codec.context.CodecContext._send_frame_and_recv
  File "av/utils.pyx", line 105, in av.utils.err_check
av.AVError: [Errno 541478725] End of file
======================================================================
ERROR: test_quality_wmv2 (pims.tests.test_display.TestExportPyAV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/soft-matter/pims/pims/tests/test_display.py", line 137, in test_quality_wmv2
    quality=1)
  File "/home/travis/build/soft-matter/pims/pims/display.py", line 160, in export_pyav
    packet = stream.encode()
  File "av/stream.pyx", line 128, in av.stream.Stream.encode
  File "av/codec/context.pyx", line 296, in av.codec.context.CodecContext.encode
  File "av/codec/context.pyx", line 209, in av.codec.context.CodecContext._send_frame_and_recv
  File "av/utils.pyx", line 105, in av.utils.err_check
av.AVError: [Errno 541478725] End of file
======================================================================
ERROR: Exported frames must equal the input exactly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/soft-matter/pims/pims/tests/test_display.py", line 185, in test_rawvideo_export
    pixel_format='bgr24')
  File "/home/travis/build/soft-matter/pims/pims/display.py", line 160, in export_pyav
    packet = stream.encode()
  File "av/stream.pyx", line 128, in av.stream.Stream.encode
  File "av/codec/context.pyx", line 296, in av.codec.context.CodecContext.encode
  File "av/codec/context.pyx", line 209, in av.codec.context.CodecContext._send_frame_and_recv
  File "av/utils.pyx", line 105, in av.utils.err_check
av.AVError: [Errno 541478725] End of file
======================================================================
ERROR: Fortran memory order must be converted.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/soft-matter/pims/pims/tests/test_display.py", line 197, in test_rgb_memorder
    pixel_format='bgr24')
  File "/home/travis/build/soft-matter/pims/pims/display.py", line 160, in export_pyav
    packet = stream.encode()
  File "av/stream.pyx", line 128, in av.stream.Stream.encode
  File "av/codec/context.pyx", line 296, in av.codec.context.CodecContext.encode
  File "av/codec/context.pyx", line 209, in av.codec.context.CodecContext._send_frame_and_recv
  File "av/utils.pyx", line 105, in av.utils.err_check
av.AVError: [Errno 541478725] End of file
======================================================================
ERROR: Remove alpha channel.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/soft-matter/pims/pims/tests/test_display.py", line 171, in test_rgba_h264
    self.export_func(self.sequence_rgba, self.tempfile, codec='libx264')
  File "/home/travis/build/soft-matter/pims/pims/display.py", line 160, in export_pyav
    packet = stream.encode()
  File "av/stream.pyx", line 128, in av.stream.Stream.encode
  File "av/codec/context.pyx", line 296, in av.codec.context.CodecContext.encode
  File "av/codec/context.pyx", line 209, in av.codec.context.CodecContext._send_frame_and_recv
  File "av/utils.pyx", line 105, in av.utils.err_check
av.AVError: [Errno 541478725] End of file
```

**Comment by caspervdw** [comment]
#313
